### ISSUE TITLE
вывод списка хэштэгов в чистом виде

### ISSUE THREAD

**Issue by aksiaaksi** [aksiaaksi/Ozon_web#1]
не понимаю как вывести список хэштэгов в чистом виде
https://github.com/aksiaaksi/Ozon_web/blob/0749b534e3555a20499501f2a1ab864f188b28a0/app/templates/index.html#L28

**Comment by coursar** [comment]
Может циклом?

**Comment by coursar** [comment]
Завтра пройдём фильтры

**Comment by aksiaaksi** [comment]
Циклом в коде HTML?
Если да, не совсем понимаю как его добавить в эту структуру с помощью jinja.

**Comment by coursar** [comment]
Можно цикл в цикле
